// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/agent/proto/route.proto

package gardener_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Condition int32

const (
	Condition_HEALTHY    Condition = 0
	Condition_HIBERNATED Condition = 1
	Condition_UNKNOWN    Condition = 2
)

// Enum value maps for Condition.
var (
	Condition_name = map[int32]string{
		0: "HEALTHY",
		1: "HIBERNATED",
		2: "UNKNOWN",
	}
	Condition_value = map[string]int32{
		"HEALTHY":    0,
		"HIBERNATED": 1,
		"UNKNOWN":    2,
	}
)

func (x Condition) Enum() *Condition {
	p := new(Condition)
	*p = x
	return p
}

func (x Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_agent_proto_route_proto_enumTypes[0].Descriptor()
}

func (Condition) Type() protoreflect.EnumType {
	return &file_internal_agent_proto_route_proto_enumTypes[0]
}

func (x Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Condition.Descriptor instead.
func (Condition) EnumDescriptor() ([]byte, []int) {
	return file_internal_agent_proto_route_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agent_proto_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_route_proto_rawDescGZIP(), []int{0}
}

type ShootList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shoots []*Shoot `protobuf:"bytes,1,rep,name=shoots,proto3" json:"shoots,omitempty"`
}

func (x *ShootList) Reset() {
	*x = ShootList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agent_proto_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootList) ProtoMessage() {}

func (x *ShootList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootList.ProtoReflect.Descriptor instead.
func (*ShootList) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_route_proto_rawDescGZIP(), []int{1}
}

func (x *ShootList) GetShoots() []*Shoot {
	if x != nil {
		return x.Shoots
	}
	return nil
}

type Shoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   string            `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels      map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Condition   Condition         `protobuf:"varint,5,opt,name=condition,proto3,enum=Condition" json:"condition,omitempty"`
}

func (x *Shoot) Reset() {
	*x = Shoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agent_proto_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shoot) ProtoMessage() {}

func (x *Shoot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shoot.ProtoReflect.Descriptor instead.
func (*Shoot) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_route_proto_rawDescGZIP(), []int{2}
}

func (x *Shoot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shoot) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Shoot) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Shoot) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Shoot) GetCondition() Condition {
	if x != nil {
		return x.Condition
	}
	return Condition_HEALTHY
}

var File_internal_agent_proto_route_proto protoreflect.FileDescriptor

var file_internal_agent_proto_route_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2b, 0x0a, 0x09, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x6f,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74,
	0x52, 0x06, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x73, 0x22, 0xc5, 0x02, 0x0a, 0x05, 0x53, 0x68, 0x6f,
	0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x2e, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x39, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x2e, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a,
	0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x2a, 0x35, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x49,
	0x42, 0x45, 0x52, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x32, 0x27, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x50, 0x72, 0x65, 0x63, 0x65, 0x6c, 0x2f, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x65, 0x72, 0x2d,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x3b, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_agent_proto_route_proto_rawDescOnce sync.Once
	file_internal_agent_proto_route_proto_rawDescData = file_internal_agent_proto_route_proto_rawDesc
)

func file_internal_agent_proto_route_proto_rawDescGZIP() []byte {
	file_internal_agent_proto_route_proto_rawDescOnce.Do(func() {
		file_internal_agent_proto_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_agent_proto_route_proto_rawDescData)
	})
	return file_internal_agent_proto_route_proto_rawDescData
}

var file_internal_agent_proto_route_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_agent_proto_route_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_agent_proto_route_proto_goTypes = []interface{}{
	(Condition)(0),    // 0: Condition
	(*Empty)(nil),     // 1: Empty
	(*ShootList)(nil), // 2: ShootList
	(*Shoot)(nil),     // 3: Shoot
	nil,               // 4: Shoot.LabelsEntry
	nil,               // 5: Shoot.AnnotationsEntry
}
var file_internal_agent_proto_route_proto_depIdxs = []int32{
	3, // 0: ShootList.shoots:type_name -> Shoot
	4, // 1: Shoot.labels:type_name -> Shoot.LabelsEntry
	5, // 2: Shoot.annotations:type_name -> Shoot.AnnotationsEntry
	0, // 3: Shoot.condition:type_name -> Condition
	1, // 4: Agent.Shoots:input_type -> Empty
	2, // 5: Agent.Shoots:output_type -> ShootList
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_agent_proto_route_proto_init() }
func file_internal_agent_proto_route_proto_init() {
	if File_internal_agent_proto_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_agent_proto_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agent_proto_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agent_proto_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_agent_proto_route_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agent_proto_route_proto_goTypes,
		DependencyIndexes: file_internal_agent_proto_route_proto_depIdxs,
		EnumInfos:         file_internal_agent_proto_route_proto_enumTypes,
		MessageInfos:      file_internal_agent_proto_route_proto_msgTypes,
	}.Build()
	File_internal_agent_proto_route_proto = out.File
	file_internal_agent_proto_route_proto_rawDesc = nil
	file_internal_agent_proto_route_proto_goTypes = nil
	file_internal_agent_proto_route_proto_depIdxs = nil
}
